const nbaSource = 'https://www.nba.com/assets/logos/teams/primary/web/';
const NBALogos = {
    ATL: nbaSource + 'ATL.svg',
    BKN: nbaSource + 'BKN.svg',
    BOS: nbaSource + 'BOS.svg',
    CHA: nbaSource + 'CHA.svg',
    CHI: nbaSource + 'CHI.svg',
    CLE: nbaSource + 'CLE.svg',
    DAL: nbaSource + 'DAL.svg',
    DEN: nbaSource + 'DEN.svg',
    DET: nbaSource + 'DET.svg',
    GSW: nbaSource + 'GSW.svg',
    HOU: nbaSource + 'HOU.svg',
    IND: nbaSource + 'IND.svg',
    LAC: nbaSource + 'LAC.svg',
    LAL: nbaSource + 'LAL.svg',
    MEM: nbaSource + 'MEM.svg',
    MIA: nbaSource + 'MIA.svg',
    MIL: nbaSource + 'MIL.svg',
    MIN: nbaSource + 'MIN.svg',
    NOP: nbaSource + 'NOP.svg',
    NYK: nbaSource + 'NYK.svg',
    OKC: nbaSource + 'OKC.svg',
    ORL: nbaSource + 'ORL.svg',
    PHI: nbaSource + 'PHI.svg',
    PHX: nbaSource + 'PHX.svg',
    POR: nbaSource + 'POR.svg',
    SAC: nbaSource + 'SAC.svg',
    SAS: nbaSource + 'SAS.svg',
    TOR: nbaSource + 'TOR.svg',
    UTA: nbaSource + 'UTA.svg',
    WAS: nbaSource + 'WAS.svg'
}

export default NBALogos;